apiVersion: v1
kind: Secret
metadata:
  name: {{ include "healthwatch.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "healthwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhousePassword | quote }}
  POSTGRES_PASSWORD:   {{ .Values.secrets.postgresPassword | quote }}
  GEMINI_API_KEY:      {{ .Values.secrets.geminiApiKey | quote }}
  GROK_API_KEY:        {{ .Values.secrets.grokApiKey | quote }}
